# Generated by Django 3.1.5 on 2023-01-10 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0009_auto_20230103_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
